name: apetito_product_api_client
description: A client for accessing the apetito Product API.
version: 1.0.1
homepage: https://github.com/Apetito-UK/dart-apetito-product-api-client

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  http: '>=0.13.0 <2.0.0'

dev_dependencies:
  lints: ^6.0.0
  oauth2: ^2.0.0
  test: ^1.17.0
